alias rg="~/.bash/fzf_rg.sh "
alias j="grep --color -nir "
alias fn="find -iname "
alias q="cd .."
alias qq="cd ../.."
alias qqq="cd ../../.."
alias qqqq="cd ../../../.."
alias qqqqq="cd ../../../../.."
alias qqqqqq="cd ../../../../../.."
alias qqqqqqq="cd ../../../../../../../"
alias ls="ls --color=auto"
alias l="ls --color=auto -la"
alias v="nvim"
alias vim="nvim"
alias bi="brew install"
alias te="open -a TextEdit"
alias bash_reload=". ~/.bash_profile"

# Git aliases start
alias gst="git status"
alias gck="git checkout"
alias gcm="git commit -m"
alias gp="git push"
alias gpt="git push --tags"
alias ga="git add"
alias gcl="git clean -fqd ."
alias gca="git commit --amend"
alias gcane="git commit --amend --no-edit"
alias gb="git branch"
alias gsts="git stash save"
alias gstp="git stash pop"
alias gsta="git stash apply"
# Git aliases end

